apiVersion: v1
kind: Service
metadata:
  name: ddc-bcss-test-subject-selector-api
  annotations:
    # Cert specified here is for nonprod. Gets replaced by service-certificate.yaml for given overlay.
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Service=bcss"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-2:730319765130:certificate/c0718115-4e22-4f48-a4aa-8c16ea86c5e6
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  labels:
    app: ddc-bcss-test-subject-selector-api
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: ddc-bcss-test-subject-selector-api
